### ISSUE TITLE
Error when trying to upload a filepath > 255 characters on windows

### ISSUE THREAD

**Issue by alextu** [JFrogDev/artifactory-cli-go#11]
To reproduce on Windows, create a long file hiearchy for example : 

```
C:\test\hahahahahahahahahaha\lalalalalalalalalala
lalallalala\yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy\haha ha\qaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\asuperlongfilenameblablalblablablalbla.txt

```

Then try to upload the base folder "test" : 

```
c:\>art upload "test\\*" "libs-release-local" --flat=false --url=http://localhost:8081/artifactory --user=**** --password=****
d
```

You should get this error and stacktrace : 

```
[Thread 1] Artifactory response: 201 Created
panic: open test\hahahahahahahahahaha\lalalalalalalalalalalalallalala\yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy\hahaha\qaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\asuperlongfil
enameblablalblablablalbla.txt: The system cannot find the path specified.

goroutine 5 [running]:
github.com/JFrogDev/artifactory-cli-go/utils.CheckError(0xc944c0, 0xc082144300)
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/utils/utils.go:10 +0x52
github.com/JFrogDev/artifactory-cli-go/commands.uploadFile(0xc08205d0e0, 0x115, 0xc0821602c0, 0x14a, 0x0, 0x0, 0xc0820051a0, 0x5,
0xc0820051c0, 0x8, ...)
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/upload.go:164 +0x190
github.com/JFrogDev/artifactory-cli-go/commands.Upload.func1(0x4, 0x3, 0xc082056ba0, 0x22, 0xc082058800, 0x4, 0x4, 0x0, 0x0, 0xc08
20051a0, ...)
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/upload.go:25 +0x1a2
created by github.com/JFrogDev/artifactory-cli-go/commands.Upload
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/upload.go:28 +0x1f0

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc082005a6c)
        c:/go/src/runtime/sema.go:43 +0x2d
sync.(*WaitGroup).Wait(0xc082005a60)
        c:/go/src/sync/waitgroup.go:126 +0xbb
github.com/JFrogDev/artifactory-cli-go/commands.Upload(0xc082056ba0, 0x22, 0xc082004280, 0x7, 0xc082002780, 0x12, 0xc082000001, 0x
0, 0x0, 0xc0820051a0, ...)
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/upload.go:30 +0x225
main.upload(0xc0820820f0)
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/art.go:242 +0x2f1
main.main.func2(0xc0820820f0)
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/art.go:48 +0x28
github.com/codegangsta/cli.Command.Run(0x7f23d0, 0x6, 0x0, 0x0, 0xc082004c60, 0x1, 0x1, 0x844720, 0x1f, 0x0, ...)
        C:/Users/Shani/gopath/src/github.com/codegangsta/cli/command.go:127 +0x1059
github.com/codegangsta/cli.(*App).Run(0xc08207e200, 0xc082058000, 0x8, 0x8, 0x0, 0x0)
        C:/Users/Shani/gopath/src/github.com/codegangsta/cli/app.go:159 +0xc36
main.main()
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/art.go:62 +0x737

goroutine 6 [runnable]:
os.(*File).Close(0xc0820d2000, 0x0, 0x0)
        c:/go/src/os/file_windows.go:158
github.com/JFrogDev/artifactory-cli-go/commands.uploadFile(0xc0820103f0, 0x8b, 0xc0820b4000, 0xc0, 0x0, 0x0, 0xc0820051a0, 0x5, 0x
c0820051c0, 0x8, ...)
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/upload.go:188 +0x488
github.com/JFrogDev/artifactory-cli-go/commands.Upload.func1(0x4, 0x3, 0xc082056ba0, 0x22, 0xc082058800, 0x4, 0x4, 0x0, 0x0, 0xc08
20051a0, ...)
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/upload.go:25 +0x1a2
created by github.com/JFrogDev/artifactory-cli-go/commands.Upload
        C:/Users/Shani/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/upload.go:28 +0x1f0

goroutine 11 [select]:
net/http.(*persistConn).readLoop(0xc082140000)
        c:/go/src/net/http/transport.go:976 +0xace
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:685 +0xc7f

goroutine 13 [select]:
net/http.(*persistConn).readLoop(0xc08212c000)
        c:/go/src/net/http/transport.go:976 +0xace
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:685 +0xc7f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc082140000)
        c:/go/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:686 +0xca4

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0xc08212c000)
        c:/go/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:686 +0xca4

goroutine 34 [select]:
net/http.(*persistConn).readLoop(0xc0820864d0)
        c:/go/src/net/http/transport.go:976 +0xace
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:685 +0xc7f

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc0820864d0)
        c:/go/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:686 +0xca4




```

**Comment by VivaLaPanda** [comment]
This problem still exists two years later. 👎

**Comment by eyalbe4** [comment]
@VivaLaPanda,
This project is no longer maintained and has been replaced by [JFrog CLI](https://github.com/JFrog/jfrog-cli-go) a long time ago.
