### ISSUE TITLE
Error when using self signed certs

### ISSUE THREAD

**Issue by kholloway** [JFrogDev/artifactory-cli-go#9]
Doing a `art config` using my companies internal artifactory URL I get the error message below.
It clearly doesn't like the self signed company cert, however I do have the certs imported into my Mac keychain and in the shell in a cert bundle that fixes things like curl and other tools but doesn't seem to work with Golang binaries. Is there a simple fix to expose a cert bundle to Golang tools or is this a larger issue?

art version 1.3.0 (via Homebrew)
Mac OS X: 10.10.5

Thanks!

```
Password: panic: Get https://redacted/api/security/encryptedPassword: x509: certificate signed by unknown authority
```

```
goroutine 1 [running]:
github.com/JFrogDev/artifactory-cli-go/utils.CheckError(0xa6d9f0, 0xc820471f80)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/utils/utils.go:25 +0x4b
github.com/JFrogDev/artifactory-cli-go/utils.Send(0x459968, 0x3, 0xc820016b00, 0x39, 0x0, 0x0, 0x0, 0x0, 0xc82000b720, 0x1b, ...)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/utils/ioUtils.go:147 +0x38c
github.com/JFrogDev/artifactory-cli-go/utils.SendGet(0xc820016b00, 0x39, 0x0, 0xc82000b720, 0x1b, 0xc820011400, 0x7, 0xc820011420, 0x8, 0x0, ...)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/utils/ioUtils.go:116 +0x9c
github.com/JFrogDev/artifactory-cli-go/utils.GetEncryptedPasswordFromArtifactory(0xc82000f270, 0xc8200c2fa0, 0x0, 0x0)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/utils/artifactoryUtils.go:71 +0xbb
github.com/JFrogDev/artifactory-cli-go/commands.encryptPassword(0xc82000f270, 0xc82000b700)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/commands/config.go:86 +0x39
github.com/JFrogDev/artifactory-cli-go/commands.Config(0xc82000f270, 0x450101)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/commands/config.go:30 +0x30f
main.config(0xc8200970e0)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/art/main.go:268 +0x4b1
main.main.func1(0xc8200970e0)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/art/main.go:30 +0x21
github.com/JFrogDev/artifactory-cli-go/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0x45b4f0, 0x6, 0x0, 0x0, 0xc820010ea0, 0x1, 0x1, 0x45b4f0, 0x6, 0x0, ...)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/Godeps/_workspace/src/github.com/codegangsta/cli/com
mand.go:137 +0x107e
github.com/JFrogDev/artifactory-cli-go/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc820096ea0, 0xc82000a5e0, 0x2, 0x2, 0x0, 0x0)
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/Godeps/_workspace/src/github.com/codegangsta/cli/app
.go:176 +0xfff
main.main()
        /private/tmp/artifactory-cli-go20160106-50997-aa066h/artifactory-cli-go-1.3.0/src/github.com/JFrogDev/artifactory-cli-go/art/main.go:53 +0x43d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by jackspirou** [comment]
https://github.com/golang/go/issues/13335 raises the issue of making `crypto/x509.systemRootsPool` a publicly accessible method in the https://golang.org/pkg/crypto/x509/ package.

**Comment by jackspirou** [comment]
I have a working version here https://github.com/jackspirou/artifactory-cli-go, but it uses the `vendor` directory instead of Godeps.  The vendor tool I use is https://github.com/govend/govend.

The relevant lines changed were 
- https://github.com/jackspirou/artifactory-cli-go/blob/master/utils/ioUtils.go#L88-L93
- https://github.com/jackspirou/artifactory-cli-go/blob/master/utils/ioUtils.go#L153-L158

**Comment by eyalbe4** [comment]
Thanks @kholloway and @jackspirou.
We will address this issue soon.

**Comment by TamirHadad** [comment]
Hi @kholloway and @jackspirou, 
Since The Artifactory CLI is deprecated and replaced with the new <a href = https://www.jfrog.com/getcli/ >JFrog CLI</a>.
 <a href = https://www.jfrog.com/getcli/ >JFrog CLI</a> is an evolution of the old tool.
<a href = https://www.jfrog.com/getcli/ >JFrog CLI</a> added support for <a href =  https://www.jfrog.com/confluence/display/RTF/JFrog+CLI#JFrogCLI-UsingSelf-signedSSLCertificates> self sign certificates </a>. 

We recommend migrating to <a href = https://github.com/JFrogDev/jfrog-cli-go> JFrog CLI.
